### ISSUE TITLE
What to do as a repository member ?

### ISSUE THREAD

**Issue by Ayowel** [Ricain/new#8]
Hi.

Thank you for adding me to the repository, however I'd like to be sure of what I may/may not do here.
Including, but not limited to:

* Branch
    * Create and push new branch (naming convention ?)
    * Merge branch (into master ?)
* Pull Request
    * Validate others pull requests
    * Validate my pull requests
* ...

**Comment by Ricain** [comment]
Hello, I am preparing my wedding and I will be in honey moon in September, I will not have time to review PRs. So yes your main goal is to validate and merge PRs (even your own) and new functionalities. You may create and merge branchs if you feel is needed.

> With great power comes great responsibility 😎 

Enjoy and thank for your help 😄
